port: :8081

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

mysql:
  host: 127.0.0.1
  port: 3306
  user: ""
  password: ""
  db: chat_game

kafka:
  host: localhost
  port: 9092
  topic: chat_game
