port: :8081

redis:
  host: redis.zest-all.orb.local
  port: 6379
  password: ""
  db: 0

mysql:
  dsn: "root:zest0108@tcp(db.zest-all.orb.local:3306)/chat_game?charset=utf8mb4&parseTime=True&loc=Local"

kafka:
  host: localhost
  port: 9092
  topic: chat_game
